name: main
on: [push]
jobs:
  main:
    name: main
    runs-on: ubuntu-latest
    steps:
      - name: main
        uses: ./
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
