name: Build
on: [push]
jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: publish
        uses: ./
        env:
          TEST_VAR: hello there
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
