name: main
on: [push]
jobs:
  main:
    name: main
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install prereqs
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install -y opam m4 make
          sudo npm install -g netlify-cli
      - name: setup opam
        run: |
          rm -rf ~/.opam
          opam init --auto-setup
          opam update
      - name: install odig
        run: |
          opam install -y odig
      - name: install opam packages
        run: |
          opam install -y $(cat pkg-list)
      - name: build docs
        run: |
          opam --version
          eval $(opam config env)
          odig odoc $(cat pkg-list)
      - name: publish
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          eval $(opam config env)
          netlify deploy --prod --dir "$(odig cache path)"/html


      #- name: main
      #  uses: ./
      #  env:
      #    NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #    NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
